### PR TITLE
Dummy commit to test travis

### PR DESCRIPTION
**Pull request by felix91gr**
- [ ] Project is actively maintained
- [ ] Linux support is stable or at least planned
- [ ] If it's a library, it has tests
- [ ] Project entry is being added in alphabetical order

### CODE REVIEW

**Comment by felix91gr** [comment]
Let's see how this goes @vknabel :D

**Comment by felix91gr** [comment]
Hmm, it seems it's missing an env. variable: [logs](https://travis-ci.com/felix91gr/awesome-system-swift/builds/75793257?utm_source=github_status&utm_medium=notification)

**Comment by vknabel** [comment]
I sent you the env variable on Twitter.

The script searches for expressions like `* [danger-swift](https://github.com/danger/danger-swift): Stop saying "you forgot to …" in code **review**.` within the diff.
Only these projects will be tested. (I actually wanted to test this for danger-swift 😅)

You could add a project from #13 if you like.
You can see some comments within the testing PR: https://github.com/vknabel/awesome-system-swift/pull/1#issuecomment-395815046

**Comment by felix91gr** [comment]
> You can see some comments within the testing PR

The comments look awesome! :heart_eyes: 

> I sent you the env variable on Twitter.

I'm guessing you don't put it here because it must be kept secret. I'm going to check on Travis' settings, it probably goes there :thinking:

**Comment by felix91gr** [comment]
Yup, stored it secretly under Travis' configuration. Let's see how it goes now!

Also:

> The script searches for expressions like * [danger-swift](https://github.com/danger/danger-swift): Stop saying "you forgot to …" in code **review**. within the diff.
Only these projects will be tested. (I actually wanted to test this for danger-swift :sweat_smile:)

I see, that's actually very nice ^^
I've sat up a weekly cron job. Would it run the entire list? That would be ideal I think, just in case some of the repos make a breaking change :)

**Comment by felix91gr** [comment]
It passed! Awesome :D

**Pull request closed without merging**
