### PR TITLE
Use HTML <details> to make the "why testing" explanation collapsable

### PR DESCRIPTION
**Pull request by felix91gr**

### CODE REVIEW

**Comment by felix91gr** [comment]
@vknabel how do you think this looks? The idea of making it expandable/collapsable is to fit the idea that the explanation is optional for the reader. For this I'm stepping out of Markdown and using `<details>`, which might not be the best. But I think the tradeoff is worth it, what do you think? :)

**Comment by felix91gr** [comment]
This might be useful for frameworks that have many standalone modules, like Vapor and Perfect. That way we can make expandable lists that show them without cluttering the section they're in :thinking:

**Comment by felix91gr** [comment]
> shouldn’t these Frameworks maintain their own summaries? Maybe we could add another section just linking to different (more specific) project lists?

I think I prefer to have the features written directly here, because then it's easier for the user to find what they're looking for (instead of having to go check if their need is listed under the framework's page somewhere). 
OTOH, conciseness would be a concern. Some of those frameworks may be just way too big at times. Maybe a middle ground could be good? Having listed here the most general tools available from the frameworks, and linking to their detailed lists as well.

I'm not sure either way.

> Not sure about this as our rationale is quite short. But when using the detail tag, we wouldn’t have to be as brief as possible like before. Losing this constraint might be a benefit.

That's true! Okay, what about an issue to brainstorm this? I'm going to open one s.t. we can come up with a better one.

**Comment by felix91gr** [comment]
Update: made #18

**Comment by vknabel** [comment]
> I think I prefer to have the features written directly here, because then it's easier for the user to find what they're looking for (instead of having to go check if their need is listed under the framework's page somewhere).
OTOH, conciseness would be a concern. Some of those frameworks may be just way too big at times. Maybe a middle ground could be good? Having listed here the most general tools available from the frameworks, and linking to their detailed lists as well.

That actually sounds great. So general libs will be directly under the categories (with use cases outside the repo’s use case), less general one that fit together go under the link to the main project (use case specific, e.g. server only) and framework specific projects won’t be linked by us, right?

**Pull request merged**
