### PR TITLE
Adds CLSwift

### PR DESCRIPTION
**Pull request by twof**
https://github.com/twof/CLSwift

### CODE REVIEW

**Comment by vknabel** [comment]
@twof thanks for the PR and sorry for the delay.
As I currently can't test your project locally: does it work on linux?

**Comment by felix91gr** [comment]
I plan on testing it as soon as possible. Today my toolchain stopped working for some reason, so for now I can't use `swift build` nor `swift test`. I'm starting an Ubuntu VM as we speak, so I should be able to test it at some point today :)

**Comment by felix91gr** [comment]
Allright. Here's the summary:

1. CLSwift was missing a couple of declarations in the test suite that didn't let it run tests under Linux.
2. [I fixed it in a PR](https://github.com/twof/CLSwift/pull/10).
3. I ran the test suite with those changes, and all tests pass on Linux. Good job! It appears to be already fully cross platform ;)

Thanks for the PR!

**Comment by twof** [comment]
Accepted your PR. Thanks @felix91gr !

**Pull request merged**
