### PR TITLE
Removed some redundant assertions about the libs

### PR DESCRIPTION
**Pull request by felix91gr**
Since so many _do_ support Linux, I think we should make it implicit... and maybe make a statement in the first lines of the document?

But anyway, the thing is, most of the libs listed here do support Linux already. The ones we're listing that don't are few, and are working on it. I think we can omit the "Runs on Darwin and Linux" part because most of them do. We can include that part if it's maybe necessary for reassurance, like for SDE, which is surrounded by libs which aren't complete on Linux yet.

What do you think?

### CODE REVIEW

**Comment by felix91gr** [comment]
Also: these wording changes for TraceLog are done in #27, that's why it's being omitted on this PR's changes :)

**Comment by vknabel** [comment]
I agree. Since this repo is a collection of projects that also support Linux, we don’t need to repeat ourselves. I think telling users that "yes, even this supports Linux" when it’s not obvious is good.

What's currently missing is the "everything supports Linux" sentence in the introduction.

**Comment by felix91gr** [comment]
_Note: I had to make a PR from `master` to this branch because git or github was stepping over the changes made in #27. Now that that's been normalized, all is well._

---

> What's currently missing is the "everything supports Linux" sentence in the introduction.

Indeed. I've now added a note at the beginning of the index talking about this. How does it look?

**Comment by felix91gr** [comment]
:boat:

**Pull request merged**
