### PR TITLE
Adding TraceLog, GeoFeatures, and StickyLocking.

### PR DESCRIPTION
**Pull request by tonystone**
Félix, adding a few more multiplatform frameworks. They didn't seem to fit any of the existing categories so I created a few extras.  Feel free to reorganize.

- [ ✔︎] Project is actively maintained
- [✔︎] Linux support is stable or at least planned
- [ ✔︎] If it's a library, it has tests
- [✔︎] Project entry is being added in alphabetical order

<--
**Why are tests required for libraries?**
Libraries, **unlike apps**, can't be run to check that they work as intended.
Therefore, tests are essential to maintain them.
Tests are also very convenient to check that they work on all supported platforms.
-->

### CODE REVIEW

**Comment by felix91gr** [comment]
Allright. Here's my review summary:

* **GeoFeatures**: jesus christ, that library looks incredible. And with 1106 tests, nonetheless. I think we will add it, for sure. Do you have any projects that use it, to check out what can be done with it?
* **TraceLog**: are you sure it's up-to-date? It asked me to use Swift 3.0. I checked `master` out. Still, it passed its tests when I compiled it as Swift 4.0.
* **StickyLocking**: it passes everything, but what does it do? Swift doesn't have 1st class threads. I assume you're extending `Dispatch`'s threads with thread-coordination primitives like MutexLocks and Signals like C#'s `lock` and `AutoResetEvent`? That would actually be really cool.

---

Btw, regarding GeoFeatures, I'd recommend trying out [SwiftCheck](https://github.com/typelift/SwiftCheck). The concept of property testing lends itself really _really_ well to math and geometry libraries :)

**Comment by tonystone** [comment]
Thanks @felix91gr.  To answer your questions.

- **GeoFeatures**: is a pure swift rewrite of an Objective-C/C++ library I wrote called of course GeoFeatures (you can find the original here (https://github.com/tonystone/geofeatures). The original was written at the Climate Corporation and is the heart of all the maps and behind the scenes geometry in the app (you can check it out here https://climate.com/). I based the original on boost/Geometry and decided, based on a lot of requests, that there is a need and place for a pure swift version.  So a team and I started out on the journey of making GeoFeatures 2 which is what is on the list.  I did consider putting both on there and if you'd like we can do that.  I do plan on releasing an early beta of GeoFeatures2 which in Cocoapods will replace GeoFeatures.
- **TraceLog**: I'll check this issue out and fix it.  Thanks for letting me know.
- **StickyLocking**: Yes, sticky locking can coordinate the backing threads of GCDs queues but also remember that pthreads are available to Swift on all current platforms as well.  I'm currently writing up more documentation with examples and stuff about how it can be used.  In a complex example though consider trying to manage the internals of a database (btw, I have a database background which is where this comes from).  You have a database that consists of multiple files and each file has multiple pages of rows.  You want to maximize the concurrency of reads and writes to the entire hierarchy not simply lock the entire structure exclusively to write (database -> file -> page -> row).  Sticky Locking allows you to lock all the levels and allow certain levels to continue reading until exclusive access is needed by other threads.  This is the same type of locking system used in Sybase, MSSQL server, and more major DBs.  The concepts were originally developed by Jim Grey while at IBM.  You can read more in his research paper (https://sites.fas.harvard.edu/~cs265/papers/gray-1976.pdf).  
---
Thanks for the heads up on SwiftCheck, it's looks very useful.  I'll consider using it in the future for sure.

**Comment by tonystone** [comment]
@felix91gr, thanks for the heads up on TraceLog, I went ahead and gave it a full upgrade to Swift 4.1 and released it as 3.0.0.

**Comment by felix91gr** [comment]
Awesome :)

I have to ask as well: how close are the libraries to production-ready? From here it looks like GeoFeatures2 isn't fully baked yet, TraceLog looks complete as far as I can see, and StickyLocking looks like it is... not released, but maybe complete?

Basically: if you were a 3rd party developer, how easy would these libraries be to use in a new project?

**Comment by tonystone** [comment]
Hi @felix91gr, on the production-ready question.
 
- **TraceLo**:  100% production-ready.  It's running in many apps I created including the climate app I listed about plus about 260 I don't know by name (according to CocoaPods).
- **GeoFeatures***: GeoFeatures1 is running in production on many applications but as GeoFeatues2 has not been released yet.  I do plan on releasing a beta shortly (within a few weeks or so) that contains the core, wkt, GeoJSN, and visualization.  We'll follow on with the algorithms such as union, intersection, etc.
- **StickyLocking**: Complete, but not yet released.  Plan to release it in beta shortly.  I want to release it concurrently with StickyEncoding (https://github.com/stickytools/sticky-encoding) which still requires some documentation and readme updates.

All the projects support SPM and CocoaPods so they are very easy to use in a project at the moment.

**Comment by vknabel** [comment]
Hi @tonystone, thanks for your contribution and sorry for the delay! 
We decided to merge TraceLock now and the other two once they have officially been released in the near future.
Just ping us create a new PR. We will merge it then.

**Comment by tonystone** [comment]
No worries, thanks @vknabel @felix91gr, I'll follow up after they are released.

**Pull request merged**
