### PR TITLE
Extended the index, added tags and refined classification

### PR DESCRIPTION
**Pull request by felix91gr**
Added most of the entries described [here](https://github.com/felix91gr/awesome-system-swift/issues/13).
Added tags to ease search.
Refined classification.
**TODO**: 
- [x] Add SDG libraries
- [x] Smooth out the resulting structure and wording after my changes.

### CODE REVIEW

**Comment by felix91gr** [comment]
I'll need a review but after I finish the details here. I marked most of what I'm missing with a `_todo_`

**Comment by felix91gr** [comment]
Okay I think I'm more or less done. What do you think?

**Comment by felix91gr** [comment]
I have 2 `_todo_` left:
* One is for Compression, a library that looks good but I don't know if is production-ready or not yet. I asked in their issues about it. If we don't get a response, we can add it later instead of now.
* The other one is for ReactiveSwift. I really don't know what to put in the description, so I'll ask you to help me with that :sweat_smile:

**Comment by vknabel** [comment]
ReactiveSwift is within the same section as Result and PromiseKit: that‘s fine!

One might say:
Result + async = PromiseKit
Result + async + Sequence = ReactiveSwift

**Comment by felix91gr** [comment]
Allright, compression [isn't complete yet](https://github.com/tris-foundation/compression/issues/15). It has decompression but not compression. So I'll take it out for this PR.

---

> One might say:
> Result + async = PromiseKit
> Result + async + Sequence = ReactiveSwift

I see! Then how about something like this for ReactiveSwift:

[ReactiveSwift](): cross platform, reactive programming. `Result + async + Sequence = ReactiveSwift`

---

Regarding RxSwift, it appears to be supported on Linux but the documentation doesn't say much about it. It builds allright, but `swift test` doesn't work (at least on Linux). In order to run the tests, it appears to be that you have to run the `AllTestz` module's binary: `.build/x86_64-unknown-linux/debug/AllTestz`.

I've posted an [issue there](https://github.com/ReactiveX/RxSwift/issues/1637). Maybe Linux is indeed supported like that. Maybe it's not officially supported. We'll see :)

**Comment by felix91gr** [comment]
I've completed the description of `ReactiveSwift`.

The RxSwift folks [haven't answered yet](https://github.com/ReactiveX/RxSwift/issues/1637), so I think we should add it later when/if they respond. I also tried asking in the Slack and someone sent me to the ios forums of RxSwift, which left me very confused (I was like ":thinking: _But I want to run it on Linux..._ :thinking:"). Anyway... they must have a different pace. They'll answer at their time, and then, I think we should add it if it's supported outside of Darwin :)

I think this PR is ready, then. The only thing I've left is this: I've put the items in the "Workflow-enabler Frameworks" list not in alphabetical order, but rather, clustered by what kind of workflow they enable. I think I could do one of the following:
* Order the list alphabetically. This follows the guidelines but leaves the different libraries out of context. (I don't like this one too much)
* Order the items in the clusters alphabetically. This allows them to be clustered, but orders the items that belong to the same context. (I like this one, this is the "default" in my mind). It clashes with the guidelines, though.
* Make a subsection for the clusters. Something like this:

### Workflow-enabler Frameworks
> *Tags: BDD, testing, reactive, promise, async, result*
* **Asyncronous and Reactive Programming**
    * [AsyncNinja](https://github.com/AsyncNinja/AsyncNinja): primitives for enabling concurrency and reactive programming.
    * [Deferred](https://github.com/bignerdranch/Deferred): a small **futures** library.
    * [PromiseKit](https://github.com/mxcl/PromiseKit/): a complete implementation of **promises**, allowing for easy **asyncronous** programming.
    * [ReactiveSwift](https://github.com/ReactiveCocoa/ReactiveSwift): cross platform, **reactive** programming. `Result + async + Sequence = ReactiveSwift`
* **Behavior Driven Development**
    * [Nimble](https://github.com/Quick/Nimble): **matcher** and **testing** counterpart for Quick.
    * [Quick](https://github.com/Quick/Quick): a **BDD** framework.
    * [Spectre](https://github.com/kylef/Spectre): a **BDD** framework and test runner for Swift.
* [Result](https://github.com/antitypical/Result): microframework for modeling and handling errors in code.
* [SwiftCheck](https://github.com/typelift/SwiftCheck): a powerful library for **Property Testing**. Inspired by Haskell's QuickCheck.

--- 

What do you think?

**Comment by vknabel** [comment]
I would prefer to keep the alphabetic order, but grouping similar libraries should be put together, too.
It should always be clear where to put new libs, therefore the alphabetic order.

I would prefer the subheadings approach. Not sure why.

Regarding the sections: what do you think of renaming the BDD section to Testing and moving SwiftCheck to that one, too?

**Comment by felix91gr** [comment]
> Regarding the sections: what do you think of renaming the BDD section to Testing and moving SwiftCheck to that one, too?

BDD is an extension of TDD, right? Fitting both under the same umbrella makes a lot of sense.

> I would prefer the subheadings approach. Not sure why.

Ditto. I think it's cleaner. The indentation seems to be less relevant if the subheadings are there. Subheadings for the win :)

**Comment by felix91gr** [comment]
Also: the [RxSwift folks answered](https://github.com/ReactiveX/RxSwift/issues/1637), so I think we should add them. I think I should make a draft after this PR to add it, together with a note on how to run its custom testing scripts. If they were using `swift test`, I'd add it directly here, but I think it's best to add it later because it's a special case (and this PR is large enough).

**Comment by felix91gr** [comment]
I put "Testing and Behavior Driven Development" instead of just "Testing". I wanted to put "Testing", but I didn't quite like it for some reason. Then I thought "Test Driven Development", but then again BDD tries to separate itself from the limitations of TDD. And so... yeah. I dunno. Names.

**Comment by felix91gr** [comment]
:boat:

**Pull request merged**
