### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vknabel**
Added some CLIs and frameworks I regularly use and sorted entries in alphabetical order.

**Disclaimer:** I am biased regarding Archery as it is my own project. If you wish I will remove the entry.

### CODE REVIEW

**Comment by felix91gr** [comment]
Awesome!
Alphabetical order is already so much nicer ^^

I'm reviewing it right now. I mostly want to check whether Beak, Marathon, SwiftFormat and SwiftLint run on Linux :)
If they don't, we can ask what's the plan and maybe give them some pointers if they ask for it. For example, Benedikt Terhechte made [a script to use Docker to test SourceKittenDaemon](https://github.com/terhechte/SourceKittenDaemon#linux).

> I am biased regarding Archery as it is my own project. If you wish I will remove the entry.

Good disclaimer! But I think it should stay. It looks like a good and well maintained project. And it also runs on Linux! So it already passes all the checks if you ask me :)

**Comment by felix91gr** [comment]
Update:
* Marathon [offers instructions for Linux](https://github.com/JohnSundell/Marathon#on-linux) and after testing it, it looks good. I posted the issues I saw in their forums.
* Sourcery (which I know Krzysztof wanted to port to Linux) [have a milestone in mind](https://github.com/krzysztofzablocki/Sourcery/milestone/2) which is super awesome to hear :)

**Comment by felix91gr** [comment]
Allright... here is my update on the other ones:

* Beak has [an issue regarding `Strings`](https://github.com/yonaskolb/Beak/issues/22). Also they don't have a `LinuxMain.swift` test file, so it looks like they don't support it atm.
* SwiftFormat... I can't even run `swift build`. It seems to compile in some other way. I posted an [issue](https://github.com/nicklockwood/SwiftFormat/issues/240) there to know what's going on.
* I fiddled with SwiftLint to make it compile, and it does, but SourceKit crashes. Maybe I've got a problem in my setup. I [asked for help there as well](https://github.com/realm/SwiftLint/issues/2147).

**Comment by felix91gr** [comment]
So all in all, I think we should definitely keep:
* Marathon
* Sourcery

And wait and see what the other three answer, and add them if there's support or intention to have support for, Linux.

What do you think? :)

**Comment by vknabel** [comment]
I totally agree with you. I just forgot to test every single tool. 🙈

* I removed Beak and SwiftFormat. 
* I also linked the Linux milestone to Sourcery and the PR to langserver-swift.
* Regarding the issued bugs, I assumed they will be fixed soon (the SwiftLint guys are so fast 😮)

> For example, Benedikt Terhechte made a script to use Docker to test SourceKittenDaemon.

Thanks for the link! Just wondering if there is a site tracking diffs between Linux and Darwin support or some polyfills to fix the diffs?

**Comment by felix91gr** [comment]
> I just forgot to test every single tool. :see_no_evil: 

:smile: no worries!

> (the SwiftLint guys are so fast :open_mouth:)

I know right?

> Just wondering if there is a site tracking diffs between Linux and Darwin support or some polyfills to fix the diffs?

Polydiff as in, a:

- [ ] Checklist
- [ ] of
- [ ] diffs?

> It would be awesome if we could just include one single magic library which implements missing or different parts to keep all platforms the same until they actually are.

I completely agree! So far, the missing pieces seem to be:
1. `Foundation`, which is [missing some pieces](https://github.com/apple/swift-corelibs-foundation/blob/master/Docs/Status.md) but [planned for completion](https://forums.swift.org/t/shouldn-t-foundation-give-off-warnings-when-nsunimplemented-is-bound-to-appear/11576/8?u=felix91gr).
2. `SourceKit` ease of use. Since Swift 3.1 or 3.2, when Norio Nomura made a Pull Request to the compiler that made `SourceKit` build under Linux, it's much easier to use on Linux. You just have to install a Swift toolchain, and then follow the [`SourceKitten` instructions](https://github.com/jpsim/SourceKitten#installation) such that it's accessible to the SourceKitten framework. It's a hassle, but it's much better than it was a year ago :)
3. Toolchain: installing a toolchain isn't that hard, but switching between them is. [swiftenv](https://github.com/kylef/swiftenv) apparently provides help with this, which sounds awesome! I want to test it soon, it probably can be added to the index.
4. Packages: installing Swift packages (like SwiftLint) appears to be hard, specially if you want to be able to [switch versions or settings](https://github.com/realm/SwiftLint/issues/732#issuecomment-339502688). I'm not too knowledgeable on this, but it seems like a pain point from what I've seen.

All in all, the ideal thing would be to use something like `apt-get` to install the toolchains and packages. `SourceKit` support is getting better, and it should benefit from better toolchain installation support. `Foundation` is a slow train, but it's getting better. 

I think we can help, specially with the installation steps. I'll brb after lunch, but I've seen discussions about `apt-get` on the forums. Til' then!

**Comment by felix91gr** [comment]
Btw, wanna be a collaborator? :)

**Comment by vknabel** [comment]
The 'magic library' would be a polyfill or shim (not sure 100% about the difference). JS has thousands of these.

> the missing pieces seem to be:
Great summary!

> Packages: installing Swift packages (like SwiftLint) appears to be hard, specially if you want to be able to switch versions or settings. I'm not too knowledgeable on this, but it seems like a pain point from what I've seen.

Not sure about installing one package in multiple versions, but [Mint](https://github.com/yonaskolb/Mint) makes it really easy to install SPM projects in specific versions. 

> SourceKit support is getting better, and it should benefit from better toolchain installation support

Yes SourceKit support is **way** better. I never want to compile swift twice just to get one single library again.

> it was about snap, which I don't know but sounds good.

Definitely going to try this.

**Pull request merged**
