### PR TITLE
Checklist for new Projects #7

### PR DESCRIPTION
**Pull request by vknabel**
This PR provides the following changes as discussed in #7 
* the new PR template for github
* Adds a notice to the readme

### CODE REVIEW

**Comment by vknabel** [comment]
Totally agree! "alphabetically correct" was the wrong grammar in the right language. 😅

> it needs an answer to the question "Why?" somewhere

We could put this into the README to keep the template as short as possible.

**Comment by vknabel** [comment]
I am not completely happy regarding the wording, yet. Do you have some suggestions?

**Comment by felix91gr** [comment]
I'd change it slightly to something like this:
> Libraries, **unlike apps**, can't be run to check that they work as intended.
> Therefore, tests are essential to maintain them.
> Tests are also very convenient to check that they work on all supported platforms.

**Comment by vknabel** [comment]
Much better now :)

**Comment by felix91gr** [comment]
I think it's ready. Do you prefer it like this:

  - Project is actively maintained
  - Linux support is stable or at least planned.
    > **Why are tests required for libraries?**
    > Libraries, **unlike apps**, can't be run to check that they work as intended.
    > Therefore, tests are essential to maintain them.
    > Tests are also very convenient to check that they work on all supported platforms.
  - If it's a library, it has tests

Or like this?

  - Project is actively maintained
  - Linux support is stable or at least planned.
  - If it's a library, it has tests
    > **Why are tests required for libraries?**
    > Libraries, **unlike apps**, can't be run to check that they work as intended.
    > Therefore, tests are essential to maintain them.
    > Tests are also very convenient to check that they work on all supported platforms.

**Comment by vknabel** [comment]
I asked myself the same question, but I decided to keep the same order for README and the PR template.
Would you prefer to change it to be aligned?

**Comment by felix91gr** [comment]
I prefer the second one, because then the question and answers appear at the same time that the reader might be thinking about them :slightly_smiling_face:

**Comment by vknabel** [comment]
In the PR template, too?

**Comment by felix91gr** [comment]
I think the template is just right with the comment at the bottom :)

**Comment by felix91gr** [comment]
:tada:

**Pull request merged**
