### PR TITLE
Add Beak

### PR DESCRIPTION
**Pull request by vknabel**
- [x] Project is actively maintained
- [x] Linux support is stable or at least planned
- [x] If it's a library, it has tests
- [x] Project entry is being added in alphabetical order

As https://github.com/yonaskolb/Beak/issues/22 has been resolved, it should now support Linux.
Although we might need to wait for the next release of Beak before merging this PR.

### CODE REVIEW

**Comment by felix91gr** [comment]
Thanks for making this PR! I was very busy these last few days :relieved: 

> Although we might need to wait for the next release of Beak before merging this PR.

I agree :)

**Comment by vknabel** [comment]
Oh yes, CL UI tool is definitely wrong.
Though I wouldn't create a new subcategory for now as beak, marathon and mint serve different ways to do very similar tasks, where workspace is a specialized use case implementation of those. archery's idea is the execution around metadata and is acutally built on mint and has plugins for beak, marathon and mint.
So all these tools have something in common.

**Comment by felix91gr** [comment]
> So all these tools have something in common.

I see. I will leave it to you, then. You know more about them than I do ^^

Is there a better classification than "Other Dev Tools" for those 4?

**Comment by vknabel** [comment]
The only ideas I could come up would be too specific to justify their own category for now

**Pull request merged**
